### ISSUE TITLE
goss_addtl_dirs broken with a trailing slash

### ISSUE THREAD

**Issue by slavaaaaaaaaaa** [naftulikay/ansible-role-degoss#29]
`goss_addtl_dirs` breaks when there's a trailing slash in the specified string. E.g.:

works: `goss_addtl_dirs: [goss.d]`
doesn't work: `goss_addtl_dirs: [goss.d/]`

**Comment by naftulikay** [comment]
#33 should prevent this, but please re-verify and re-open if this is still the case.
