### ISSUE TITLE
Make Cleanup Handlers Always Run

### ISSUE THREAD

**Issue by naftulikay** [naftulikay/ansible-role-degoss#3]
Right now if tests fail, handlers don't run and things aren't cleaned up.

**Comment by naftulikay** [comment]
A solution to this outside of `force_handlers` is to basically allow the task to fail, store the result in a variable, and fail after cleanup.

**Comment by sagagliardo** [comment]
Moved cleanup just into the main tasks run instead of running it as a handler. If nothing changes, handlers don't run -- at all. So it's better they just always run at the end.

See https://github.com/naftulikay/ansible-role-degoss/pull/4

**Comment by naftulikay** [comment]
Closed by #6.
